#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itim.TRS.InstallerLib.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Catalogue")]
	public partial class IRSecurityDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDatabaseVersion(DatabaseVersion instance);
    partial void UpdateDatabaseVersion(DatabaseVersion instance);
    partial void DeleteDatabaseVersion(DatabaseVersion instance);
    partial void InsertSystemParameter(SystemParameter instance);
    partial void UpdateSystemParameter(SystemParameter instance);
    partial void DeleteSystemParameter(SystemParameter instance);
    partial void InsertServer(Server instance);
    partial void UpdateServer(Server instance);
    partial void DeleteServer(Server instance);
    partial void InsertInstalledHotfix(InstalledHotfix instance);
    partial void UpdateInstalledHotfix(InstalledHotfix instance);
    partial void DeleteInstalledHotfix(InstalledHotfix instance);
    #endregion
		
		public IRSecurityDataContext() : 
				base(global::Itim.TRS.InstallerLib.Properties.Settings.Default.CatalogueConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public IRSecurityDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IRSecurityDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IRSecurityDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IRSecurityDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DatabaseVersion> DatabaseVersions
		{
			get
			{
				return this.GetTable<DatabaseVersion>();
			}
		}
		
		public System.Data.Linq.Table<SystemParameter> SystemParameters
		{
			get
			{
				return this.GetTable<SystemParameter>();
			}
		}
		
		public System.Data.Linq.Table<Server> Servers
		{
			get
			{
				return this.GetTable<Server>();
			}
		}
        public System.Data.Linq.Table<TRSInstance> TRSInstances
        {
            get
            {
                return this.GetTable<TRSInstance>();
            }
        }


        public System.Data.Linq.Table<InstalledHotfix> InstalledHotfixes
		{
			get
			{
				return this.GetTable<InstalledHotfix>();
			}
		}

        public System.Data.Linq.Table<InstalledHotfixDetails> InstalledHotfixDetails
        {
            get
            {
                return this.GetTable<InstalledHotfixDetails>();
            }
        }
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="IRSecurity.DatabaseVersion")]
	public partial class DatabaseVersion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pkDatabaseVersionId;
		
		private int _fkSystemApplicationId;
		
		private string _VersionNumber;
		
		private string _Description;
		
		private System.DateTime _ReleaseDate;
		
		private System.DateTime _DeploymentDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpkDatabaseVersionIdChanging(int value);
    partial void OnpkDatabaseVersionIdChanged();
    partial void OnfkSystemApplicationIdChanging(int value);
    partial void OnfkSystemApplicationIdChanged();
    partial void OnVersionNumberChanging(string value);
    partial void OnVersionNumberChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnReleaseDateChanging(System.DateTime value);
    partial void OnReleaseDateChanged();
    partial void OnDeploymentDateChanging(System.DateTime value);
    partial void OnDeploymentDateChanged();
    #endregion
		
		public DatabaseVersion()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pkDatabaseVersionId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pkDatabaseVersionId
		{
			get
			{
				return this._pkDatabaseVersionId;
			}
			set
			{
				if ((this._pkDatabaseVersionId != value))
				{
					this.OnpkDatabaseVersionIdChanging(value);
					this.SendPropertyChanging();
					this._pkDatabaseVersionId = value;
					this.SendPropertyChanged("pkDatabaseVersionId");
					this.OnpkDatabaseVersionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkSystemApplicationId", DbType="Int NOT NULL")]
		public int fkSystemApplicationId
		{
			get
			{
				return this._fkSystemApplicationId;
			}
			set
			{
				if ((this._fkSystemApplicationId != value))
				{
					this.OnfkSystemApplicationIdChanging(value);
					this.SendPropertyChanging();
					this._fkSystemApplicationId = value;
					this.SendPropertyChanged("fkSystemApplicationId");
					this.OnfkSystemApplicationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionNumber", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string VersionNumber
		{
			get
			{
				return this._VersionNumber;
			}
			set
			{
				if ((this._VersionNumber != value))
				{
					this.OnVersionNumberChanging(value);
					this.SendPropertyChanging();
					this._VersionNumber = value;
					this.SendPropertyChanged("VersionNumber");
					this.OnVersionNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(256)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReleaseDate", DbType="DateTime NOT NULL")]
		public System.DateTime ReleaseDate
		{
			get
			{
				return this._ReleaseDate;
			}
			set
			{
				if ((this._ReleaseDate != value))
				{
					this.OnReleaseDateChanging(value);
					this.SendPropertyChanging();
					this._ReleaseDate = value;
					this.SendPropertyChanged("ReleaseDate");
					this.OnReleaseDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeploymentDate", DbType="DateTime NOT NULL")]
		public System.DateTime DeploymentDate
		{
			get
			{
				return this._DeploymentDate;
			}
			set
			{
				if ((this._DeploymentDate != value))
				{
					this.OnDeploymentDateChanging(value);
					this.SendPropertyChanging();
					this._DeploymentDate = value;
					this.SendPropertyChanged("DeploymentDate");
					this.OnDeploymentDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SystemParameter")]
	public partial class SystemParameter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pkSystemParameterID;
		
		private string _Description;
		
		private string _Value;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpkSystemParameterIDChanging(int value);
    partial void OnpkSystemParameterIDChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnValueChanging(string value);
    partial void OnValueChanged();
    #endregion
		
		public SystemParameter()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pkSystemParameterID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pkSystemParameterID
		{
			get
			{
				return this._pkSystemParameterID;
			}
			set
			{
				if ((this._pkSystemParameterID != value))
				{
					this.OnpkSystemParameterIDChanging(value);
					this.SendPropertyChanging();
					this._pkSystemParameterID = value;
					this.SendPropertyChanged("pkSystemParameterID");
					this.OnpkSystemParameterIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this.OnValueChanging(value);
					this.SendPropertyChanging();
					this._Value = value;
					this.SendPropertyChanged("Value");
					this.OnValueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="IRSecurity.Server")]
	public partial class Server : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pkServerId;
		
		private string _IP;
		
		private string _Name;
		
		private string _Description;
        private int _fkTRSInstanceId;

        private bool _IsDatabaseServer;
        #region Extensibility Method Definitions
        partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpkServerIdChanging(int value);
    partial void OnpkServerIdChanged();

        partial void OnfkTRSInstanceIdChanging(int value);
        partial void OnfkTRSInstanceIdChanged();
        partial void OnIPChanging(string value);
    partial void OnIPChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
        partial void OnIsDatabaseServerChanging(bool value);
        partial void OnIsDatabaseServerChanged();
        #endregion

        public Server()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pkServerId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pkServerId
		{
			get
			{
				return this._pkServerId;
			}
			set
			{
				if ((this._pkServerId != value))
				{
					this.OnpkServerIdChanging(value);
					this.SendPropertyChanging();
					this._pkServerId = value;
					this.SendPropertyChanged("pkServerId");
					this.OnpkServerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string IP
		{
			get
			{
				return this._IP;
			}
			set
			{
				if ((this._IP != value))
				{
					this.OnIPChanging(value);
					this.SendPropertyChanging();
					this._IP = value;
					this.SendPropertyChanged("IP");
					this.OnIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_fkTRSInstanceId", DbType = "Int", CanBeNull = true)]
        public int fkTRSInstanceId
        {
            get
            {
                return this._fkTRSInstanceId;
            }
            set
            {
                if ((this._fkTRSInstanceId != value))
                {
                    this.OnfkTRSInstanceIdChanging(value);
                    this.SendPropertyChanging();
                    this._fkTRSInstanceId = value;
                    this.SendPropertyChanged("fkTRSInstanceId");
                    this.OnfkTRSInstanceIdChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_IsDatabaseServer", DbType = "Bit", CanBeNull = true)]
        public bool IsDatabaseServer
        {
            get
            {
                return this._IsDatabaseServer;
            }
            set
            {
                if ((this._IsDatabaseServer != value))
                {
                    this.OnIsDatabaseServerChanging(value);
                    this.SendPropertyChanging();
                    this._IsDatabaseServer = value;
                    this.SendPropertyChanged("IsDatabaseServer");
                    this.OnIsDatabaseServerChanged();
                }
            }
        }


        public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="IRSecurity.InstalledHotfix")]
	public partial class InstalledHotfix : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pkInstalledHotfixId;
		
		private string _HotfixVersion;
		
		private string _Description;
		
		private System.DateTime _ReleaseDate;
		
		private System.DateTime _DeploymentDate;
		
		private bool _IsForWebServer;
		
		private bool _IsForAppServer;
		
		private bool _IsForDBServer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpkInstalledHotfixIdChanging(int value);
    partial void OnpkInstalledHotfixIdChanged();
    partial void OnHotfixVersionChanging(string value);
    partial void OnHotfixVersionChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnReleaseDateChanging(System.DateTime value);
    partial void OnReleaseDateChanged();
    partial void OnDeploymentDateChanging(System.DateTime value);
    partial void OnDeploymentDateChanged();
    partial void OnIsForWebServerChanging(bool value);
    partial void OnIsForWebServerChanged();
    partial void OnIsForAppServerChanging(bool value);
    partial void OnIsForAppServerChanged();
    partial void OnIsForDBServerChanging(bool value);
    partial void OnIsForDBServerChanged();
    #endregion
		
		public InstalledHotfix()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pkInstalledHotfixId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pkInstalledHotfixId
		{
			get
			{
				return this._pkInstalledHotfixId;
			}
			set
			{
				if ((this._pkInstalledHotfixId != value))
				{
					this.OnpkInstalledHotfixIdChanging(value);
					this.SendPropertyChanging();
					this._pkInstalledHotfixId = value;
					this.SendPropertyChanged("pkInstalledHotfixId");
					this.OnpkInstalledHotfixIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HotfixVersion", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string HotfixVersion
		{
			get
			{
				return this._HotfixVersion;
			}
			set
			{
				if ((this._HotfixVersion != value))
				{
					this.OnHotfixVersionChanging(value);
					this.SendPropertyChanging();
					this._HotfixVersion = value;
					this.SendPropertyChanged("HotfixVersion");
					this.OnHotfixVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReleaseDate", DbType="DateTime NOT NULL")]
		public System.DateTime ReleaseDate
		{
			get
			{
				return this._ReleaseDate;
			}
			set
			{
				if ((this._ReleaseDate != value))
				{
					this.OnReleaseDateChanging(value);
					this.SendPropertyChanging();
					this._ReleaseDate = value;
					this.SendPropertyChanged("ReleaseDate");
					this.OnReleaseDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeploymentDate", DbType="DateTime NOT NULL")]
		public System.DateTime DeploymentDate
		{
			get
			{
				return this._DeploymentDate;
			}
			set
			{
				if ((this._DeploymentDate != value))
				{
					this.OnDeploymentDateChanging(value);
					this.SendPropertyChanging();
					this._DeploymentDate = value;
					this.SendPropertyChanged("DeploymentDate");
					this.OnDeploymentDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsForWebServer", DbType="Bit NOT NULL")]
		public bool IsForWebServer
		{
			get
			{
				return this._IsForWebServer;
			}
			set
			{
				if ((this._IsForWebServer != value))
				{
					this.OnIsForWebServerChanging(value);
					this.SendPropertyChanging();
					this._IsForWebServer = value;
					this.SendPropertyChanged("IsForWebServer");
					this.OnIsForWebServerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsForAppServer", DbType="Bit NOT NULL")]
		public bool IsForAppServer
		{
			get
			{
				return this._IsForAppServer;
			}
			set
			{
				if ((this._IsForAppServer != value))
				{
					this.OnIsForAppServerChanging(value);
					this.SendPropertyChanging();
					this._IsForAppServer = value;
					this.SendPropertyChanged("IsForAppServer");
					this.OnIsForAppServerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsForDBServer", DbType="Bit NOT NULL")]
		public bool IsForDBServer
		{
			get
			{
				return this._IsForDBServer;
			}
			set
			{
				if ((this._IsForDBServer != value))
				{
					this.OnIsForDBServerChanging(value);
					this.SendPropertyChanging();
					this._IsForDBServer = value;
					this.SendPropertyChanged("IsForDBServer");
					this.OnIsForDBServerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}


    [global::System.Data.Linq.Mapping.TableAttribute(Name = "IRSecurity.InstalledHotfixDetails")]
    public partial class InstalledHotfixDetails : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _pkInstalledHotfixDetailId;
        private int _fkInstalledHotfixId;
        private string _Artifacts;
        private bool _IsForWebServer;

        private bool _IsForAppServer;

        private bool _IsForDBServer;



        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnpkInstalledHotfixDetailIdChanging(int value);
        partial void OnpkInstalledHotfixDetailIdChanged();
        partial void OnfkInstalledHotfixIdChanging(int value);
        partial void OnfkInstalledHotfixIdChanged();
        partial void OnArtifactsChanging(string value);
        partial void OnArtifactsChanged();
        partial void OnIsForWebServerChanging(bool value);
        partial void OnIsForWebServerChanged();
        partial void OnIsForAppServerChanging(bool value);
        partial void OnIsForAppServerChanged();
        partial void OnIsForDBServerChanging(bool value);
        partial void OnIsForDBServerChanged();

        #endregion

        public InstalledHotfixDetails()
        {
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_pkInstalledHotfixDetailId", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int pkInstalledHotfixDetailId
        {
            get
            {
                return this._pkInstalledHotfixDetailId;
            }
            set
            {
                if ((this._pkInstalledHotfixDetailId != value))
                {
                    this.OnpkInstalledHotfixDetailIdChanging(value);
                    this.SendPropertyChanging();
                    this._pkInstalledHotfixDetailId = value;
                    this.SendPropertyChanged("pkInstalledHotfixDetailId");
                    this.OnpkInstalledHotfixDetailIdChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_fkInstalledHotfixId", DbType = "Int", CanBeNull = true)]
        public int fkInstalledHotfixId
        {
            get
            {
                return this._fkInstalledHotfixId;
            }
            set
            {
                if ((this._fkInstalledHotfixId != value))
                {
                    this.OnfkInstalledHotfixIdChanging(value);
                    this.SendPropertyChanging();
                    this._fkInstalledHotfixId = value;
                    this.SendPropertyChanged("fkInstalledHotfixId");
                    this.OnfkInstalledHotfixIdChanged();
                }
            }
        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Artifacts", DbType = "VarChar(500) ", CanBeNull = true)]
        public string Artifacts
        {
            get
            {
                return this._Artifacts;
            }
            set
            {
                if ((this._Artifacts != value))
                {
                    this.OnArtifactsChanging(value);
                    this.SendPropertyChanging();
                    this._Artifacts = value;
                    this.SendPropertyChanged("Artifacts");
                    this.OnArtifactsChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_IsForWebServer", DbType = "Bit NOT NULL")]
        public bool IsForWebServer
        {
            get
            {
                return this._IsForWebServer;
            }
            set
            {
                if ((this._IsForWebServer != value))
                {
                    this.OnIsForWebServerChanging(value);
                    this.SendPropertyChanging();
                    this._IsForWebServer = value;
                    this.SendPropertyChanged("IsForWebServer");
                    this.OnIsForWebServerChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_IsForAppServer", DbType = "Bit NOT NULL")]
        public bool IsForAppServer
        {
            get
            {
                return this._IsForAppServer;
            }
            set
            {
                if ((this._IsForAppServer != value))
                {
                    this.OnIsForAppServerChanging(value);
                    this.SendPropertyChanging();
                    this._IsForAppServer = value;
                    this.SendPropertyChanged("IsForAppServer");
                    this.OnIsForAppServerChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_IsForDBServer", DbType = "Bit NOT NULL")]
        public bool IsForDBServer
        {
            get
            {
                return this._IsForDBServer;
            }
            set
            {
                if ((this._IsForDBServer != value))
                {
                    this.OnIsForDBServerChanging(value);
                    this.SendPropertyChanging();
                    this._IsForDBServer = value;
                    this.SendPropertyChanged("IsForDBServer");
                    this.OnIsForDBServerChanged();
                }
            }
        }


        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }














    [global::System.Data.Linq.Mapping.TableAttribute(Name = "IRSecurity.TRSInstance")]
    public partial class TRSInstance : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _pkTRSInstanceId;

        private bool _IsSelfInstance;
        private bool _IsMasterInstance;
        private string _InstanceCode;
        private string _InstanceName;

        private string _InstanceURI;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnpkTRSInstanceIdChanging(int value);
        partial void OnpkTRSInstanceIdChanged();
        partial void OnIPChanging(string value);
        partial void OnIPChanged();
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        partial void OnInstanceURIChanging(string value);
        partial void OnInstanceURIChanged();
        partial void OnInstanceCodeChanging(string value);
        partial void OnInstanceCodeChanged();
        partial void OnIsSelfInstanceChanging(bool value);
        partial void OnIsSelfInstanceChanged();
        partial void OnIsMasterInstanceChanging(bool value);
        partial void OnIsMasterInstanceChanged();
        #endregion

        public TRSInstance()
        {
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_pkTRSInstanceId", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int pkTRSInstanceId
        {
            get
            {
                return this._pkTRSInstanceId;
            }
            set
            {
                if ((this._pkTRSInstanceId != value))
                {
                    this.OnpkTRSInstanceIdChanging(value);
                    this.SendPropertyChanging();
                    this._pkTRSInstanceId = value;
                    this.SendPropertyChanged("pkServerId");
                    this.OnpkTRSInstanceIdChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_IsSelfInstance", DbType = "Bit", CanBeNull = true)]
        public bool IsSelfInstance
        {
            get
            {
                return this._IsSelfInstance;
            }
            set
            {
                if ((this._IsSelfInstance != value))
                {
                    this.OnIsSelfInstanceChanging(value);
                    this.SendPropertyChanging();
                    this._IsSelfInstance = value;
                    this.SendPropertyChanged("IsSelfInstance");
                    this.OnIsSelfInstanceChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_IsMasterInstance", DbType = "Bit", CanBeNull = true)]
        public bool IsMasterInstance
        {
            get
            {
                return this._IsMasterInstance;
            }
            set
            {
                if ((this._IsMasterInstance != value))
                {
                    this.OnIsMasterInstanceChanging(value);
                    this.SendPropertyChanging();
                    this._IsMasterInstance = value;
                    this.SendPropertyChanged("IsMasterInstance");
                    this.OnIsMasterInstanceChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_InstanceCode", DbType = "VarChar(500) NOT NULL", CanBeNull = false)]
        public string InstanceCode
        {
            get
            {
                return this._InstanceCode;
            }
            set
            {
                if ((this._InstanceCode != value))
                {
                    this.OnInstanceCodeChanging(value);
                    this.SendPropertyChanging();
                    this._InstanceCode = value;
                    this.SendPropertyChanged("InstanceCode");
                    this.OnInstanceCodeChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_InstanceName", DbType = "VarChar(500) NOT NULL", CanBeNull = false)]
        public string InstanceName
        {
            get
            {
                return this._InstanceName;
            }
            set
            {
                if ((this._InstanceName != value))
                {
                    this.OnNameChanging(value);
                    this.SendPropertyChanging();
                    this._InstanceName = value;
                    this.SendPropertyChanged("InstanceName");
                    this.OnNameChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_InstanceURI", DbType = "VarChar(500) NOT NULL", CanBeNull = false)]
        public string InstanceURI
        {
            get
            {
                return this._InstanceURI;
            }
            set
            {
                if ((this._InstanceURI != value))
                {
                    this.OnInstanceURIChanging(value);
                    this.SendPropertyChanging();
                    this._InstanceURI = value;
                    this.SendPropertyChanged("InstanceURI");
                    this.OnInstanceURIChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }


}
#pragma warning restore 1591
