//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itim.TRS.InstallerLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Itim.TRS.InstallerLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} does not contain the Applications directory. Any App files referenced in the configuration file should be located in the Applications folder..
        /// </summary>
        internal static string ERR_APP_DIR_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_APP_DIR_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a customer-specific {1} that is not intended for ‘{0}’. {1} installation has been terminated..
        /// </summary>
        internal static string ERR_CUSTOMER_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("ERR_CUSTOMER_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} does not contain the Database directory. Any sql script files referenced in the configuration file should be located in the Database folder..
        /// </summary>
        internal static string ERR_DATABASE_DIR_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_DATABASE_DIR_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The executable {0} was not found. This is required to continue the installation. Installation has been terminated..
        /// </summary>
        internal static string ERR_EXE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_EXE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation directory was not found..
        /// </summary>
        internal static string ERR_INSTALL_DIR_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_INSTALL_DIR_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified Installation Folder does not appear to be a valid The Retail Suite installation folder. Please specify the correct installation folder. Installation has been terminated..
        /// </summary>
        internal static string ERR_INSTALLATION_CORRUPT {
            get {
                return ResourceManager.GetString("ERR_INSTALLATION_CORRUPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string names &quot;Catalogue&quot; is missing in the configuration file {0}.exe.config. The installer requires this connection string to connect with the database..
        /// </summary>
        internal static string ERR_MISSING_CATALOGUE_CONNECTION_STRING {
            get {
                return ResourceManager.GetString("ERR_MISSING_CATALOGUE_CONNECTION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string section was missing in the configuration file {0}.exe.config..
        /// </summary>
        internal static string ERR_MISSING_CONNECTION_STRING_SECTION {
            get {
                return ResourceManager.GetString("ERR_MISSING_CONNECTION_STRING_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation of hotfix {0} cannot continue. Following required hotfixes are missing: {1}.
        /// </summary>
        internal static string ERR_MISSING_PREREQUISITE_HOTFIXES {
            get {
                return ResourceManager.GetString("ERR_MISSING_PREREQUISITE_HOTFIXES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation of Patch {0} cannot continue. Following required Patches are missing: {1}.
        /// </summary>
        internal static string ERR_MISSING_PREREQUISITE_PatchES {
            get {
                return ResourceManager.GetString("ERR_MISSING_PREREQUISITE_PatchES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {3} (v{0}) is not compatible with the version installed on this machine (v{1}). This {3} can only be installed over the following release versions: {2}.
        /// </summary>
        internal static string ERR_MISSING_REQUIRED_RELEASES {
            get {
                return ResourceManager.GetString("ERR_MISSING_REQUIRED_RELEASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation mode could not be detected. Verify that the installation directory has a valid TRS installation. Terminating installation..
        /// </summary>
        internal static string ERR_NONE_INSTALLATION_MODE {
            get {
                return ResourceManager.GetString("ERR_NONE_INSTALLATION_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Patch (v{0}) you are trying to install is already present on this deployment. Patch installation has been terminated..
        /// </summary>
        internal static string ERR_Patch_ALREADY_INSTALLED {
            get {
                return ResourceManager.GetString("ERR_Patch_ALREADY_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading Prerequiste configuration section from the configuration file. Make sure that the section exists and is correctly defined..
        /// </summary>
        internal static string ERR_PREREQ_CONFIG {
            get {
                return ResourceManager.GetString("ERR_PREREQ_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation was aborted by the user..
        /// </summary>
        internal static string ERR_USER_ABORT {
            get {
                return ResourceManager.GetString("ERR_USER_ABORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning installation for hotfix v{0} - {1}.
        /// </summary>
        internal static string INF_BEGIN_HOTFIX_INSTALL {
            get {
                return ResourceManager.GetString("INF_BEGIN_HOTFIX_INSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning installation for Patch v{0} - {1}.
        /// </summary>
        internal static string INF_BEGIN_Patch_INSTALL {
            get {
                return ResourceManager.GetString("INF_BEGIN_Patch_INSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensuring that file system and databases are in synch..
        /// </summary>
        internal static string INF_CHECK_FS_DB_SYNCH {
            get {
                return ResourceManager.GetString("INF_CHECK_FS_DB_SYNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking pre-requisite hotfixes....
        /// </summary>
        internal static string INF_CHECK_HOTFIX_COMPAT {
            get {
                return ResourceManager.GetString("INF_CHECK_HOTFIX_COMPAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking pre-requisite Patches....
        /// </summary>
        internal static string INF_CHECK_Patch_COMPAT {
            get {
                return ResourceManager.GetString("INF_CHECK_Patch_COMPAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking compatibilty with installed releases....
        /// </summary>
        internal static string INF_CHECK_RELEASE_COMPAT {
            get {
                return ResourceManager.GetString("INF_CHECK_RELEASE_COMPAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking compatibility for this client....
        /// </summary>
        internal static string INF_CHECK_SUPPORTED_CLIENTS {
            get {
                return ResourceManager.GetString("INF_CHECK_SUPPORTED_CLIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading connection string from.
        /// </summary>
        internal static string INF_CONFIG_FILE {
            get {
                return ResourceManager.GetString("INF_CONFIG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using connection string {0}.
        /// </summary>
        internal static string INF_CONN_STRING {
            get {
                return ResourceManager.GetString("INF_CONN_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files copied..
        /// </summary>
        internal static string INF_COPY_COMPLETE {
            get {
                return ResourceManager.GetString("INF_COPY_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying patch files....
        /// </summary>
        internal static string INF_COPY_FILES {
            get {
                return ResourceManager.GetString("INF_COPY_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting temporary installation files.
        /// </summary>
        internal static string INF_DELETE_TEMP {
            get {
                return ResourceManager.GetString("INF_DELETE_TEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting installation mode....
        /// </summary>
        internal static string INF_DETECT_INSTALL_MODE {
            get {
                return ResourceManager.GetString("INF_DETECT_INSTALL_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing sql scripts {0}....
        /// </summary>
        internal static string INF_EXECUTING_SQLSCRIPT {
            get {
                return ResourceManager.GetString("INF_EXECUTING_SQLSCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} copied..
        /// </summary>
        internal static string INF_FILE_COPIED {
            get {
                return ResourceManager.GetString("INF_FILE_COPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizing installation.
        /// </summary>
        internal static string INF_FINALIZE_INSTALL {
            get {
                return ResourceManager.GetString("INF_FINALIZE_INSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Hotfix (v{0}) is already installed on {1}..
        /// </summary>
        internal static string INF_HOTFIX_ALREADY_INSTALL {
            get {
                return ResourceManager.GetString("INF_HOTFIX_ALREADY_INSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation completed successfully.
        /// </summary>
        internal static string INF_INSTALL_COMPLETE {
            get {
                return ResourceManager.GetString("INF_INSTALL_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation mode is {0}.
        /// </summary>
        internal static string INF_INSTALL_MODE {
            get {
                return ResourceManager.GetString("INF_INSTALL_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading configuration file....
        /// </summary>
        internal static string INF_READ_CONFIG {
            get {
                return ResourceManager.GetString("INF_READ_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflex installation mode is {0}.
        /// </summary>
        internal static string INF_REFLEX_INSTALL_MODE {
            get {
                return ResourceManager.GetString("INF_REFLEX_INSTALL_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting Reflex....
        /// </summary>
        internal static string INF_RESTART_REFLEX {
            get {
                return ResourceManager.GetString("INF_RESTART_REFLEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback Complete.
        /// </summary>
        internal static string INF_ROLLBACK_END {
            get {
                return ResourceManager.GetString("INF_ROLLBACK_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing old files....
        /// </summary>
        internal static string INF_ROLLBACK_FILE_COPY {
            get {
                return ResourceManager.GetString("INF_ROLLBACK_FILE_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolling back installation....
        /// </summary>
        internal static string INF_ROLLBACK_START {
            get {
                return ResourceManager.GetString("INF_ROLLBACK_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing rfgr....
        /// </summary>
        internal static string INF_RUN_RFGR {
            get {
                return ResourceManager.GetString("INF_RUN_RFGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing rfsdll....
        /// </summary>
        internal static string INF_RUN_RFSDLL {
            get {
                return ResourceManager.GetString("INF_RUN_RFSDLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for connection string in the destination directory....
        /// </summary>
        internal static string INF_SEARCH_CON_STRING {
            get {
                return ResourceManager.GetString("INF_SEARCH_CON_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down Reflex....
        /// </summary>
        internal static string INF_SHUTDOWN_REFLEX {
            get {
                return ResourceManager.GetString("INF_SHUTDOWN_REFLEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script {0} successfully executed..
        /// </summary>
        internal static string INF_SQLSCRIPT_COMPLETED {
            get {
                return ResourceManager.GetString("INF_SQLSCRIPT_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying installation directory....
        /// </summary>
        internal static string INF_VERIFY_INSTALLDIR {
            get {
                return ResourceManager.GetString("INF_VERIFY_INSTALLDIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying prerequisites....
        /// </summary>
        internal static string INF_VERIFY_PREREQ {
            get {
                return ResourceManager.GetString("INF_VERIFY_PREREQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patches on the file system and database are out of sync..
        /// </summary>
        internal static string WRN_DB_FILE_OUTOFSYNC {
            get {
                return ResourceManager.GetString("WRN_DB_FILE_OUTOFSYNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following fixes are not found on the database:.
        /// </summary>
        internal static string WRN_HOTFIX_NOT_ON_DB {
            get {
                return ResourceManager.GetString("WRN_HOTFIX_NOT_ON_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following fixes are not found on the file system:.
        /// </summary>
        internal static string WRN_HOTFIX_NOT_ON_FS {
            get {
                return ResourceManager.GetString("WRN_HOTFIX_NOT_ON_FS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following fixes are not found on the database:.
        /// </summary>
        internal static string WRN_Patch_NOT_ON_DB {
            get {
                return ResourceManager.GetString("WRN_Patch_NOT_ON_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following fixes are not found on the file system:.
        /// </summary>
        internal static string WRN_Patch_NOT_ON_FS {
            get {
                return ResourceManager.GetString("WRN_Patch_NOT_ON_FS", resourceCulture);
            }
        }
    }
}
