//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itim.TRS.FixInstaller.TRSFixInstallerServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TRSFixInstallerServiceRef.ITRSFixService")]
    public interface ITRSFixService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITRSFixService/InstallFix", ReplyAction="http://tempuri.org/ITRSFixService/InstallFixResponse")]
        string[] InstallFix(string filepath, string features);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITRSFixServiceChannel : Itim.TRS.FixInstaller.TRSFixInstallerServiceRef.ITRSFixService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TRSFixServiceClient : System.ServiceModel.ClientBase<Itim.TRS.FixInstaller.TRSFixInstallerServiceRef.ITRSFixService>, Itim.TRS.FixInstaller.TRSFixInstallerServiceRef.ITRSFixService {
        
        public TRSFixServiceClient() {
        }
        
        public TRSFixServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TRSFixServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TRSFixServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TRSFixServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] InstallFix(string filepath, string features) {
            return base.Channel.InstallFix(filepath, features);
        }
    }
}
